# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    target-branch: "main"
    allow:
      - dependency-type: "direct"
    commit-message:
      prefix: "dependabot github-actions update"
      include: "scope"
    labels:
      - "dependencies"
      - "github actions"

  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: weekly
    target-branch: "main"
    allow:
      - dependency-type: "direct"
    commit-message:
      prefix: "dependabot bundler update"
      include: "scope"
    labels:
      - "dependencies"
      - "ruby"
