# Minima theme configuration
remote_theme: jekyll/minima
plugins:
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-gfm-admonitions
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-relative-links
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-titles-from-headings
  - jekyll-toc

# valid social icon names can be found at https://fontawesome.com/search?ic=brands

minima:
  skin: auto
  hide_site_feed_link: true
  show_excerpts: false
  social_links:
    - title: "GitHub Pages Home"
      icon: house
      icon_pack: regular
      url: "https://blwatkins.github.io/"
    - title: "Beehiiv Newsletter"
      icon: envelope
      icon_pack: regular
      url: "https://brittniwatkins.beehiiv.com/"
    - title: "Source Code"
      icon: git-alt
      icon_pack: brands
      url: "https://github.com/blwatkins/blwatkins.github.io"
    - title: GitHub
      icon: github
      icon_pack: brands
      url: "https://github.com/blwatkins"
    - title: YouTube
      icon: youtube
      icon_pack: brands
      url: "https://www.youtube.com/channel/UCeJ-huUU2AWP0z4-HWr1BXQ"
    - title: LinkedIn
      icon: linkedin
      icon_pack: brands
      url: "https://www.linkedin.com/in/brittni-watkins/"
    - title: Ko-fi
      icon: ko-fi
      icon_pack: brands
      url: "https://ko-fi.com/brittniwatkins"
  nav_pages:
    - index.md
    - portfolio/index.md
    - ai-use.md
    - sponsor.md

title: "Brittni Watkins"
description: "Creative Technologist: Algorithmic Artist, Software Engineer, and Educator"

sass:
  quiet_deps: true
  silence_deprecations: ["import"]

exclude:
  - .github
  - .gitignore
  - .ruby-version
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor
